### ISSUE TITLE
Pandas 1.0 Options API Tweaks

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2templates#41]
**Bug Description**
[`df_to_html`](https://github.com/qiime2/q2templates/blob/6d2e26c56a618ed290e89c1983fdd1a072e7a903/q2templates/util.py#L45) sets the `display.max_colwidth` parameter to -1 to disable truncating the cell values. This parameter value (`-1`) is no longer supported, and should be replaced with `None` to opt into the same behavior

**Steps to reproduce the behavior**
1. Install pandas 1.0: `conda install -c conda-forge -c bioconda pandas=1.0`
2. 
```python
import pandas as pd
from q2templates import df_to_html

df = pd.DataFrame([])
df_to_html(df)
```
3. Observe the following error: `Value must be a nonnegative integer or None`

**Expected behavior**
No error.

**References**
1. [Busywork](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-demux/builds/65).

**Comment by andrewsanchez** [comment]
I'm confused about where pandas 1.0 is coming from.  I was under the impression that [these external dependencies](https://github.com/qiime2/environment-files/search?o=desc&q=pandas&s=indexed) are the ones that we use and test against.  I don't see pandas 1.0 being specified anywhere.

Is the goal to have tests pass with `0.25.3>=pandas<=1.0`?  Setting `display.max_colwidth` to `None` in pandas version 0.25.3 throws another `ValueError` `ValueError: Value must have type '<class 'int'>'`

**Comment by thermokarst** [comment]
> I'm confused about where pandas 1.0 is coming from

The first step in busywork is to build the conda package. The project [conda recipe](https://github.com/qiime2/q2templates/blob/master/ci/recipe/meta.yaml) specifies the details. For this particular package, I would like to point out [this line](https://github.com/qiime2/q2templates/blob/6d2e26c56a618ed290e89c1983fdd1a072e7a903/ci/recipe/meta.yaml#L24) - this tells conda to install pandas as a runtime dependency, and since there is no version specification, conda will (usually) install the newest available version. So in this case, pandas 1.0! Things get more complicated when you try and resolve many dependencies (especially when they have their own secondary and tertiary dependencies to deal with).


> Is the goal to have tests pass with `pandas>=0.25.3`?

In general, yep! I think realistically we should tighten that [pin](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications) up a bit and actually spec `pandas >=1` (or something along those lines), instead of trying to support older releases of pandas.
