### ISSUE TITLE
Test suite issue with pandas 1.5

### ISSUE THREAD

**Issue by tillea** [qiime2/q2templates#50]
**Bug Description**
Debian wants to upgrade pandas to version 1.5.  In connection with this pandas version the test suite of q2templates throws an error.  This is documented in a [bug report](https://bugs.debian.org/1024821).

**Steps to reproduce the behavior**
You can install the prerequisites (specifically pandas 1.5) as we used in the [full build log](https://launchpadlibrarian.net/633830688/buildlog_ubuntu-lunar-amd64.q2templates_2022.8.0+ds-1_BUILDING.txt.gz).  This ends with the following error:

    =================================== FAILURES ===================================
    ______________________ TestDataFrameToHTML.test_defaults _______________________

    self = <q2templates.tests.test_util.TestDataFrameToHTML testMethod=test_defaults>

        def test_defaults(self):
            df = pd.DataFrame({'col1': ['foo', 'bar', 'baz'], 'col2': [1, 2, 4.2]})
    
            obs = df_to_html(df)
    
    >       self.assertIn('border="0"', obs)
    E       AssertionError: 'border="0"' not found in '<table class="dataframe table table-striped table-hover">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>col1</th>\n      <th>col2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>foo</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n        <td>bar</td>\n      <td>2.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>baz</td>\n      <td>4.2</td>\n    </tr>\n  </tbody>\n</table>'

    q2templates/tests/test_util.py:33: AssertionError
    =========================== short test summary info ============================
    FAILED q2templates/tests/test_util.py::TestDataFrameToHTML::test_defaults - A...
    ========================= 1 failed, 2 passed in 0.33s ==========================

**Expected behavior**
Passing the test suite as with previous pandas version.

**Computation Environment**
- OS: Debian (unstable + python3-pandas from experimental)
- QIIME 2 Release: 2022.8.0

Kind regards, Andreas.

**Comment by ebolyen** [comment]
Hey @tillea,

I believe we fixed this in this PR: https://github.com/qiime2/q2templates/pull/49
You could either apply that patch, or wait for the 2022.11 release which should be out end of next week. It looks like our current version of pandas for the core distribution is `1.5.1`.

As always, thanks for the report!

**Comment by tillea** [comment]
Hi,
Am Fri, Dec 09, 2022 at 10:12:31AM -0800 schrieb Evan Bolyen:
> I believe we fixed this in this PR: https://github.com/qiime2/q2templates/pull/49
> You could either apply that patch, or wait for the 2022.11 release which should be out end of next week. It looks like our current version of pandas for the core distribution is `1.5.1`.
Thanks a lot.  I've applied the patch to the Debian package.  There is no need for an intermediate release.

> As always, thanks for the report!
You are welcome, Andreas.
